apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vsftpd.fullname" . }}
  labels:
    {{- include "vsftpd.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "vsftpd.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "vsftpd.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "vsftpd.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: ftpd
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            - name: pasv-0
              containerPort: 50000
              protocol: TCP
            - name: pasv-1
              containerPort: 50001
              protocol: TCP
            - name: pasv-2
              containerPort: 50002
              protocol: TCP
            - name: pasv-3
              containerPort: 50003
              protocol: TCP
            - name: pasv-4
              containerPort: 50004
              protocol: TCP
            - name: pasv-5
              containerPort: 50005
              protocol: TCP
            - name: pasv-6
              containerPort: 50006
              protocol: TCP
            - name: pasv-7
              containerPort: 50007
              protocol: TCP
            - name: pasv-8
              containerPort: 50008
              protocol: TCP
            - name: pasv-9
              containerPort: 50009
              protocol: TCP
            - name: pasv-10
              containerPort: 50010
              protocol: TCP
            - name: pasv-11
              containerPort: 50011
              protocol: TCP
            - name: pasv-12
              containerPort: 50012
              protocol: TCP
            - name: pasv-13
              containerPort: 50013
              protocol: TCP
            - name: pasv-14
              containerPort: 50014
              protocol: TCP
            - name: pasv-15
              containerPort: 50015
              protocol: TCP
            - name: pasv-16
              containerPort: 50016
              protocol: TCP
            - name: pasv-17
              containerPort: 50017
              protocol: TCP
            - name: pasv-18
              containerPort: 50018
              protocol: TCP
            - name: pasv-19
              containerPort: 50019
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /etc/vsftpd
            {{- with .Values.extraVolumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
        {{- if .Values.sshd.enabled }}
        - name: sshd
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: flaccid/sshd
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: sshd
              containerPort: 22
              protocol: TCP
        {{- end }}
        {{- if .Values.httphealth.enabled }}
        - name: http-health
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: flaccid/httpstaticd
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http-health
              containerPort: 8080
              protocol: TCP
        {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "vsftpd.fullname" . }}
      {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
