apiVersion: v1
kind: Service
metadata:
  name: {{ include "vsftpd.fullname" . }}
  labels:
    {{- include "vsftpd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: ftpd
      port: {{ .Values.service.port }}
      targetPort: ftpd
      protocol: TCP
    - name: pasv-0
      port: 15393
      targetPort: 15393
      nodePort: 30393
      protocol: TCP
    - name: pasv-1
      port: 15394
      targetPort: 15394
      nodePort: 30394
      protocol: TCP
  selector:
    {{- include "vsftpd.selectorLabels" . | nindent 4 }}
