apiVersion: v1
kind: Service
metadata:
  name: {{ include "vsftpd.fullname" . }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "vsftpd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: ftpd
      port: {{ .Values.service.port }}
      targetPort: ftpd
      protocol: TCP
    {{- $pasvMinPort := int .Values.service.pasvMinPort }}
    {{- $pasvMaxPort := int .Values.service.pasvMaxPort | add1 | int }}
    {{- $step := 1 }}
    {{- $pasvPorts := untilStep $pasvMinPort $pasvMaxPort $step }}
    {{- range $index, $port := $pasvPorts }}
    - name: pasv-{{ $index }}
      port: {{ $port }}
      targetPort: {{ $port }}
    {{- end }}
    {{- if .Values.sshd.enabled }}
    - name: sshd
      port: 22
      targetPort: sshd
      protocol: TCP
    {{- end }}
    {{- if .Values.httphealth.enabled }}
    - name: http-health
      port: 8080
      targetPort: http-health
      protocol: TCP
    {{- end }}
  selector:
    {{- include "vsftpd.selectorLabels" . | nindent 4 }}
