{{- if eq .Values.kind "StatefulSet" }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "vsftpd.fullname" . }}
  labels:
    {{- include "vsftpd.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "vsftpd.selectorLabels" . | nindent 6 }}
  # This headless service is required for the StatefulSet
  serviceName: "{{ include "vsftpd.fullname" . }}-headless"
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "vsftpd.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "vsftpd.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: ftpd
              containerPort: {{ .Values.service.port }}
          {{- $pasvMinPort := int .Values.service.pasvMinPort }}
          {{- $pasvMaxPort := int .Values.service.pasvMaxPort | add1 | int }}
          {{- $step := 1 }}
          {{- $pasvPorts := untilStep $pasvMinPort $pasvMaxPort $step }}
          {{- range $index, $port := $pasvPorts }}
            - name: pasv-{{ $index }}
              containerPort: {{ $port }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: {{ .Values.configMount.path }}
              subPath: {{ .Values.configMount.subPath }}
            # Mount the persistent volume for user data
            - name: {{ .Values.persistentVolume.name }}
              mountPath: {{ .Values.persistentVolume.mountPath }}
            {{- with .Values.extraVolumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
        {{- if .Values.sshd.enabled }}
        - name: sshd
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.sshd.image.repository }}:{{ .Values.sshd.image.tag }}"
          imagePullPolicy: {{ .Values.sshd.image.pullPolicy }}
          volumeMounts:
            # Also mount the persistent volume here for SSH access
            - name: {{ .Values.persistentVolume.name }}
              mountPath: {{ .Values.persistentVolume.mountPath }}
            {{- with .Values.extraVolumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: sshd
              containerPort: 22
              protocol: TCP
          {{- with .Values.sshd.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- end }}
        {{- if .Values.httphealth.enabled }}
        - name: http-health
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: flaccid/httpstaticd
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http-health
              containerPort: 8080
              protocol: TCP
        {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "vsftpd.fullname" . }}
      {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.persistentVolume.name }}
    spec:
      accessModes: {{ .Values.persistentVolume.accessModes }}
      storageClassName: {{ .Values.persistentVolume.storageClassName }}
      resources:
        requests:
          storage: {{ .Values.persistentVolume.size }}
{{- end }}
